version: "3.8"

services:
  web:
    build: .
    container_name: php_blog_project
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    restart: unless-stopped
